site:
  name: 'Турсунали blago196 - Благоустройство территории'
  site: 'https://blago196.ru'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: false
  yandexSiteVerificationId: false

# Default SEO metadata
metadata:
  title:
    default: 'Турсунали blago196 - Профессиональная укладка плитки в Екатеринбурге'
    template: '%s — Турсунали blago196'
  description: 'Укладка тротуарной плитки под ключ в Екатеринбурге и области. Гарантия качества, доступные цены. Звоните: +7 925 222 41 90.'
  keywords: 'укладка тротуарной плитки, брусчатка, Екатеринбург, Турсунали blago196, благоустройство'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'blago196.ru благо196.рф'
    images:
      - url: '~/assets/images/og-image.jpg'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@blago196'
    site: '@blago196'
    cardType: summary_large_image

i18n:
  language: ru
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
